version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - backend_net
    expose:
      - "8000"
    environment:
      - PORT=8000

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - backend_net
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  backend_net:
    driver: bridge
